version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
      - PORT=${PORT}
    networks:
      - ${NETWORK}
    ports:
      - ${PORT}:5055
    volumes:
      - ${VOLUME}:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=http"
      - "traefik.http.routers.overseerr.rule=Host(`${HOST}`)"
      - "traefik.http.middlewares.overseerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overseerr.middlewares=overseerr-https-redirect"
      - "traefik.http.routers.overseerr-secure.entrypoints=https"
      - "traefik.http.routers.overseerr-secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.overseerr-secure.tls=true"
      - "traefik.http.routers.overseerr-secure.service=overseerr"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=${NETWORK}"
    restart: unless-stopped

networks:
  ${NETWORK}:
    external: true
