services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - ${PROWLARR_NETWORK}
    ports:
      - '${PROWLARR_PORTS}:9696'
    environment:
      - PUID=${PROWLARR_PUID}
      - PGID=${PROWLARR_PGID}
      - TZ=${PROWLARR_TZ}
    volumes:
      - ${PROWLARR_VOLUME_DATA}:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.requests.entrypoints=http"
      - "traefik.http.routers.requests.rule=Host(`${PROWLARR_HOST}`)"
      - "traefik.http.middlewares.requests-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.requests.middlewares=requests-https-redirect"
      - "traefik.http.routers.requests-secure.entrypoints=https"
      - "traefik.http.routers.requests-secure.rule=Host(`${PROWLARR_HOST}`)"
      - "traefik.http.routers.requests-secure.tls=true"
      - "traefik.http.routers.requests-secure.service=requests"
      - "traefik.http.services.requests.loadbalancer.server.port=9696"
      - "traefik.docker.network=${PROWLARR_NETWORK}"
    restart: unless-stopped

networks:
  ${PROWLARR_NETWORK}:
    external: true
