version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    networks:
      - ${NETWORK}
    volumes:
      - ${UPTIME_KUMA_VOLUME}:/app/data
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    restart: always

networks:
  ${NETWORK}:
    external: true
