version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ${GUACAMOLE_CONFIG_VOLUME}:/config
    ports:
      - "${GUACAMOLE_PORT}:8080"
    environment:
      - EXTENSIONS=${GUACAMOLE_EXTENSIONS}
    restart: unless-stopped

networks:
  ${NETWORK_NAME}:
    external: true