services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - ${RADARR_NETWORK}
    ports:
      - '${RADARR_PORTS}:7878'
    environment:
      - PUID=${RADARR_PUID}
      - PGID=${RADARR_PGID}
      - TZ=${RADARR_TZ}
    volumes:
      - ${RADARR_VOLUME_CONFIG}:/config
      - ${RADARR_VOLUME_MOVIES}:/movies #optional
      - ${RADARR_VOLUME_DOWNLOADS}:/downloads #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.getmovies.entrypoints=http"
      - "traefik.http.routers.getmovies.rule=Host(`${RADARR_HOST}`)"
      - "traefik.http.middlewares.getmovies-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.getmovies.middlewares=getmovies-https-redirect"
      - "traefik.http.routers.getmovies-secure.entrypoints=https"
      - "traefik.http.routers.getmovies-secure.rule=Host(`${RADARR_HOST}`)"
      - "traefik.http.routers.getmovies-secure.tls=true"
      - "traefik.http.routers.getmovies-secure.service=getmovies"
      - "traefik.http.services.getmovies.loadbalancer.server.port=7878"
      - "traefik.docker.network=${RADARR_NETWORK}"
    restart: unless-stopped

networks:
  ${RADARR_NETWORK}:
    external: true