version: '2.1'

services:
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode-server
    networks:
      - ${NETWORK}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - HASHED_PASSWORD=${HASHED_PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}
    volumes:
      - ${CONFIG_VOLUME}:/config
      - ${SERVER_VOLUME}:/server
    ports:
      - ${EXPOSED_PORT}:8443
    restart: unless-stopped

networks:
  ${NETWORK}:
    external: true