version: '3'

services:
  db:
    image: "mysql:5.7"
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    networks:
      - ${NETWORK}
    restart: always
    environment:
      MYSQL_DATABASE: ${UVDESK_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${UVDESK_ROOT_PASSWORD}
      MYSQL_USER: ${UVDESK_DB_USER}
      MYSQL_PASSWORD: ${UVDESK_DB_PASSWORD}

  uvdesk:
    image: nuttcorp/uvdesk:latest
    depends_on:
      - db
    tty: true
    networks:
      - ${NETWORK}
    environment:
      MYSQL_USER: ${UVDESK_DB_USER}
      MYSQL_PASSWORD: ${UVDESK_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${UVDESK_ROOT_PASSWORD}
      MYSQL_DATABASE: ${UVDESK_DB_NAME}
    ports:
      - ${UVDESK_PORT}:80

volumes:
  db_data: {}

networks:
  ${NETWORK}:
    external: true