version: "3"
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${NEXTCLOUD_PORT}:80"
      - "${NEXTCLOUD_WEB_PORT}:8080"
      - "${NEXTCLOUD_TLS_PORT}:8443"
      - "${APACHE_PORT}:80"
      - "${TALK_PORT}:3478"

    environment:
      - APACHE_PORT=${APACHE_PORT}
      - APACHE_IP_BINDING=${APACHE_IP_BINDING}
      - TALK_PORT=${TALK_PORT}
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_WEB_PORT=${NEXTCLOUD_WEB_PORT}
      - NEXTCLOUD_TLS_PORT=${NEXTCLOUD_TLS_PORT}

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    external: true
