version: '3.3'
services:
    node-exporter: 
        image: prom/node-exporter:latest 
        container_name: node-exporter
        networks:
            - ${NETWORK}
        restart: unless-stopped 
        volumes: 
            - /proc:/host/proc:ro 
            - /sys:/host/sys:ro 
            - /:/rootfs:ro 
        ports: 
            - ${NODE_PORT}:9100

networks:
    ${NETWORK}:
        external: true