version: '3.3'
services:
    it-tools:
        container_name: it-tools
        restart: unless-stopped
        networks:
            - ${NETWORK}
        ports:
            - "${TOOLS_PORT}:80"
        image: 'corentinth/it-tools:latest'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.it-tools.entrypoints=http"
            - "traefik.http.routers.it-tools.rule=Host(`${HOST_NAME}`)"
            - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.it-tools.middlewares=it-tools-https-redirect"
            - "traefik.http.routers.it-tools-secure.entrypoints=https"
            - "traefik.http.routers.it-tools-secure.rule=Host(`${HOST_NAME}`)"
            - "traefik.http.routers.it-tools-secure.tls=true"
            - "traefik.http.routers.it-tools-secure.service=it-tools"
            - "traefik.http.services.it-tools.loadbalancer.server.port=80"
            - "traefik.docker.network=${NETWORK}"

networks:
  ${NETWORK}:
    external: true
